name: pythia-study
channels:
  - conda-forge
  - anaconda
dependencies:
  - pypythia
  - tabulate
  - scikit-learn
  - lightgbm
  - pip
  - pip:
    - pandas
    - bipython
#  -pylexibench
#  -pythialabelgenerator
